setwd("C:/Users/19106/Downloads/exdata_data_household_power_consumption (1)")
household_power_consumption=read.table("household_power_consumption.txt", sep=";",header=T, stringsAsFactors = F)
household_power_consumption$Date=as.POSIXct(household_power_consumption$Date,format="%d/%m/%Y")
household_power_consumption<-subset(household_power_consumption,Date >= "2007-02-01" & Date <= "2007-02-02")
numeric_vars=c("Global_active_power", "Global_reactive_power","Voltage", "Global_intensity", "Sub_metering_1","Sub_metering_2","Sub_metering_3")
household_power_consumption[numeric_vars]=sapply(household_power_consumption[numeric_vars], as.numeric)
png("plot1.png",width = 480, height=480)
hist(as.numeric(household_power_consumption$Global_active_power), col="red", xlab="Global Active Power(kilowatts)", ylab="Frequency", ylim=c(0,1200),main="Global Active Power")
dev.off()
